language: node_js
version:
- "8"
cache:
  directories:
    - node_modules
before_install:
- chmod a+x ./install.sh
install:
- ./install.sh
before_script:
  - npm install -g gulp-cli
script:
- tsc
- gulp